function input = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  INPUT = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a string array.
%
%  INPUT = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  input = importfile1("D:\Git\Advent-of-Code-2022\Day 02\input.txt", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 04-Dec-2022 13:16:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "BZ";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, "BZ", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "BZ", "EmptyFieldRule", "auto");

% Import the data
input = readmatrix(filename, opts);

end